---
name: test and coverage
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15, 1.16]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: make test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
